export const DOMAINS = [
  {
    id: 'frontend',
    name: 'Frontend',
    icon: '🎨',
    description: 'React, Vue, Angular, CSS, HTML',
    color: 'var(--color-primary)',
    avgScore: 74,
  },
  {
    id: 'backend',
    name: 'Backend',
    icon: '⚙️',
    description: 'Node.js, Python, Java, Go, APIs',
    color: 'var(--color-secondary)',
    avgScore: 71,
  },
  {
    id: 'fullstack',
    name: 'Full Stack',
    icon: '🚀',
    description: 'End-to-end web applications',
    color: 'var(--color-success)',
    avgScore: 68,
  },
  {
    id: 'mobile',
    name: 'Mobile',
    icon: '📱',
    description: 'React Native, Flutter, Swift, Kotlin',
    color: 'var(--color-warning)',
    avgScore: 72,
  },
  {
    id: 'data',
    name: 'Data Science',
    icon: '📊',
    description: 'ML, Python, TensorFlow, Analysis',
    color: 'var(--color-danger)',
    avgScore: 69,
  },
  {
    id: 'devops',
    name: 'DevOps',
    icon: '🔧',
    description: 'Docker, K8s, CI/CD, Cloud',
    color: 'var(--color-purple)',
    avgScore: 66,
  },
]

export const PRICING_PLANS = [
  {
    id: 'free',
    name: 'Free',
    price: 0,
    period: '',
    description: 'Get started with AI evaluation',
    features: [
      '3 project evaluations/month',
      'Phase 1 exams only',
      'Basic evaluation report',
      'Community certificate',
      'Public profile',
    ],
    cta: 'Get Started',
    highlighted: false,
  },
  {
    id: 'premium_monthly',
    name: 'Premium',
    price: 299,
    period: '/month',
    description: 'Full access for serious developers',
    features: [
      'Unlimited project evaluations',
      'Phase 1 + Phase 2 exams',
      'Detailed AI evaluation report',
      'PDF certificate download',
      'LinkedIn sharing',
      'No ads',
      'Priority evaluation queue',
      'Re-evaluate up to 3 times',
    ],
    cta: 'Go Premium',
    highlighted: true,
    razorpayAmount: 29900,
  },
  {
    id: 'recruiter',
    name: 'Recruiter',
    price: 999,
    period: '/month',
    description: 'For hiring teams & organizations',
    features: [
      'Everything in Premium',
      'Verify any certificate',
      'Bulk candidate evaluation',
      'Team dashboard',
      'API access',
      'Priority support',
    ],
    cta: 'Contact Sales',
    highlighted: false,
    razorpayAmount: 99900,
  },
]

export const EXAM_ROUTES_NO_ADS = ['/exam']
export const PAYMENT_ROUTES_NO_ADS = ['/pricing']
export const DASHBOARD_ROUTES_NO_ADS = ['/dashboard']
